/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacio;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class infoHoraris extends javax.swing.JPanel {
    CtrlPresentacio cp;
    String nomPlaEstudis;
    
    /**
     * Creates new form infoHorari
     */
    public infoHoraris(CtrlPresentacio cp, String nomPlaEstudis) {
        this.cp=cp;
        this.nomPlaEstudis=nomPlaEstudis;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomHorariText = new javax.swing.JTextField();
        restriccioCapacitatCheckBox = new javax.swing.JCheckBox();
        restriccioCorrequisitCheckBox = new javax.swing.JCheckBox();
        afegirRestriccioClasseButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        crearHorariButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        restriccioFaseCheckBox = new javax.swing.JCheckBox();
        afegirRestriccioGrupDiaHoraButton = new javax.swing.JButton();
        restriccioTipusAulaCheckBox = new javax.swing.JCheckBox();
        eliminarRestriccioButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setText("nomHorari");

        restriccioCapacitatCheckBox.setText("Restriccio Capacitat");


        restriccioCorrequisitCheckBox.setText("Restriccio Correquisit");

        afegirRestriccioClasseButton.setText("Afegir Restriccio Classe");
        afegirRestriccioClasseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirRestriccioClasseButtonActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdRestriccio", "Nom Aula", "Dia", "Hora", "Nom Assignatura", "Num Grup"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        crearHorariButton.setText("Crear Horari");
        crearHorariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearHorariButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        restriccioFaseCheckBox.setText("Restriccio Fase");

        afegirRestriccioGrupDiaHoraButton.setText("Afegir Restriccio GrupDiaHora");
        afegirRestriccioGrupDiaHoraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirRestriccioGrupDiaHoraButtonActionPerformed(evt);
            }
        });

        restriccioTipusAulaCheckBox.setText("Restriccio TipusAula");


        eliminarRestriccioButton.setText("Eliminar Restriccio");
        eliminarRestriccioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarRestriccioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(restriccioCapacitatCheckBox)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(nomHorariText))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(eliminarRestriccioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(afegirRestriccioGrupDiaHoraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(afegirRestriccioClasseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(restriccioCorrequisitCheckBox)
                            .addComponent(restriccioFaseCheckBox)
                            .addComponent(restriccioTipusAulaCheckBox))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crearHorariButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restriccioCapacitatCheckBox)
                    .addComponent(jLabel1)
                    .addComponent(nomHorariText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restriccioCorrequisitCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restriccioFaseCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restriccioTipusAulaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(afegirRestriccioClasseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afegirRestriccioGrupDiaHoraButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarRestriccioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crearHorariButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cp.horaris();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void afegirRestriccioClasseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirRestriccioClasseButtonActionPerformed
        infoRestriccioClasse i = new infoRestriccioClasse(cp,nomPlaEstudis);
        i.setVisible(true);
    }//GEN-LAST:event_afegirRestriccioClasseButtonActionPerformed

    private void crearHorariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearHorariButtonActionPerformed
        String nomHorari=nomHorariText.getText();
        Boolean restriccioCapacitat=restriccioCapacitatCheckBox.isSelected();
        Boolean restriccioCorrequisit=restriccioCorrequisitCheckBox.isSelected();
        Boolean restriccioFase=restriccioFaseCheckBox.isSelected();
        Boolean restriccioTipusAula=restriccioTipusAulaCheckBox.isSelected();
        ArrayList<ArrayList<String>> restriccions= new ArrayList<>();
        for(int i=0;i<jTable1.getRowCount();++i){
            ArrayList<String> valors= new ArrayList<>();
            valors.add(jTable1.getValueAt(i,0).toString());
            valors.add(jTable1.getValueAt(i,1).toString());
            valors.add(jTable1.getValueAt(i,2).toString());
            valors.add(jTable1.getValueAt(i,3).toString());      
            valors.add(jTable1.getValueAt(i,4).toString());
            valors.add(jTable1.getValueAt(i,5).toString());
            restriccions.add(valors);
        }
        cp.crearHorari(nomHorari,restriccioCapacitat,restriccioCorrequisit,restriccioFase,restriccioTipusAula,restriccions,nomPlaEstudis);
    }//GEN-LAST:event_crearHorariButtonActionPerformed

    private void eliminarRestriccioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarRestriccioButtonActionPerformed
        int col=jTable1.getSelectedColumn();
        int row=jTable1.getSelectedRow();
        if (col != -1){
            if (row != -1) {
                errorDialog ce= new errorDialog(new javax.swing.JFrame(),true,jTable1.getValueAt(row, 0).toString(),"",false);
                ce.setVisible(true);
                if(ce.getReturnStatus()==1){
                DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                tm.removeRow(jTable1.getSelectedRow());
                }
            }
        }
    }//GEN-LAST:event_eliminarRestriccioButtonActionPerformed

    private void afegirRestriccioGrupDiaHoraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirRestriccioGrupDiaHoraButtonActionPerformed
        infoRestriccioGrupDiaHora i = new infoRestriccioGrupDiaHora(cp,nomPlaEstudis);
        i.setVisible(true);
    }//GEN-LAST:event_afegirRestriccioGrupDiaHoraButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afegirRestriccioClasseButton;
    private javax.swing.JButton afegirRestriccioGrupDiaHoraButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton crearHorariButton;
    private javax.swing.JButton eliminarRestriccioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomHorariText;
    private javax.swing.JCheckBox restriccioCapacitatCheckBox;
    private javax.swing.JCheckBox restriccioCorrequisitCheckBox;
    private javax.swing.JCheckBox restriccioFaseCheckBox;
    private javax.swing.JCheckBox restriccioTipusAulaCheckBox;
    // End of variables declaration//GEN-END:variables

void afegirRestriccioTaula(String idRestriccio,String nomAula,String dia,String hora, String nomAssignatura,String numGrup){
    Boolean existeix=false;
    for(int i=0;i<jTable1.getRowCount();++i){
        if(jTable1.getValueAt(i,0).toString().equals(idRestriccio)) existeix=true;
    }
    if(!existeix){
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.addRow(new Object[]{idRestriccio,nomAula,dia,hora,nomAssignatura,numGrup});
    }
}   

}
