/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacio;

import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class vistaCalendariHorari extends javax.swing.JPanel {
    CtrlPresentacio cp;
    String nomHorari;
    String nomPlaEstudis;
    String dia;
    String classeActual[] = new String[3];
    String classe1[] = new String[3];
    String classe2[] = new String[3];
    Boolean primer=true;
    /**
     * Creates new form vistaCalendariHorari
     */
    public vistaCalendariHorari(CtrlPresentacio cp, String nomHorari, String nomPlaEstudis) {
        this.nomHorari=nomHorari;
        this.nomPlaEstudis=nomPlaEstudis;
        this.cp=cp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nomText = new javax.swing.JTextField();
        cancelButton1 = new javax.swing.JButton();
        dillunsRadioButton = new javax.swing.JRadioButton();
        dimartsRadioButton = new javax.swing.JRadioButton();
        dimecresRadioButton = new javax.swing.JRadioButton();
        dijousRadioButton = new javax.swing.JRadioButton();
        divendresRadioButton = new javax.swing.JRadioButton();
        sessio1 = new javax.swing.JTextField();
        intercanviarButton = new javax.swing.JButton();
        sessio2 = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(600, 400));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        nomText.setEditable(false);
        nomText.setBackground(new java.awt.Color(250, 250, 250));


        cancelButton1.setText("Cancel");
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(dillunsRadioButton);
        dillunsRadioButton.setText("Dilluns");
        dillunsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dillunsRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(dimartsRadioButton);
        dimartsRadioButton.setText("Dimarts");
        dimartsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimartsRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(dimecresRadioButton);
        dimecresRadioButton.setText("Dimecres");
        dimecresRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimecresRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(dijousRadioButton);
        dijousRadioButton.setText("Dijous");
        dijousRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dijousRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(divendresRadioButton);
        divendresRadioButton.setText("Divendres");
        divendresRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divendresRadioButtonActionPerformed(evt);
            }
        });

        sessio1.setEditable(false);
        sessio1.setBackground(new java.awt.Color(250, 250, 250));


        intercanviarButton.setText("Intercanviar");
        intercanviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intercanviarButtonActionPerformed(evt);
            }
        });

        sessio2.setEditable(false);
        sessio2.setBackground(new java.awt.Color(250, 250, 250));


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nomText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intercanviarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sessio2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sessio1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dillunsRadioButton)
                                .addComponent(dimartsRadioButton)
                                .addComponent(dimecresRadioButton)
                                .addComponent(dijousRadioButton)
                                .addComponent(divendresRadioButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dillunsRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(dimartsRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(dimecresRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(dijousRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(divendresRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(sessio1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sessio2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton1)
                    .addComponent(intercanviarButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        cp.horaris();
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void dillunsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dillunsRadioButtonActionPerformed
        dia="Dilluns";
        update();
    }//GEN-LAST:event_dillunsRadioButtonActionPerformed

    private void dimartsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimartsRadioButtonActionPerformed
        dia="Dimarts";
        jTable1.clearSelection();
        update();
    }//GEN-LAST:event_dimartsRadioButtonActionPerformed

    private void dimecresRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimecresRadioButtonActionPerformed
        dia="Dimecres";
        update();
    }//GEN-LAST:event_dimecresRadioButtonActionPerformed

    private void dijousRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dijousRadioButtonActionPerformed
        dia="Dijous";
        update();
    }//GEN-LAST:event_dijousRadioButtonActionPerformed

    private void divendresRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divendresRadioButtonActionPerformed
        dia="Divendres";
        update();
    }//GEN-LAST:event_divendresRadioButtonActionPerformed


    private void intercanviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intercanviarButtonActionPerformed
        if(classe1[0]!=null && classe2[0]!=null){
            Boolean fet=cp.intecanviar(classe1[0],classe1[1],classe1[2],classe2[0],classe2[1],classe2[2]);
            if(fet) update();
            else{
                errorDialog e= new errorDialog(new javax.swing.JFrame(),true,sessio1.getText(),sessio2.getText(),true);
                e.setVisible(true);
                if(e.getReturnStatus()==1){
                    cp.intercanviarObligat(classe1[0],classe1[1],classe1[2],classe2[0],classe2[1],classe2[2]);
                    update();
                }
            }
        }
    }//GEN-LAST:event_intercanviarButtonActionPerformed
    void update(){
        ArrayList<ArrayList<String>> aules=cp.getAules();
        ArrayList<String> hores=cp.getHores(nomPlaEstudis);
        
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.setRowCount(0);
        tm.setColumnCount(0);
        tm.addColumn("Hora");
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTable1.getColumnModel().getColumn(0).setMinWidth(20);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(20);
        jTable1.getColumnModel().getColumn(0).sizeWidthToFit();
                
        for(ArrayList<String> a:aules){
            String nomAula=a.get(0);
            tm.addColumn(nomAula);
        }
        
        for(String h:hores){
            ArrayList<String>sessions=new ArrayList<>();
            sessions.add(h);
            for(ArrayList<String> a:aules){
                sessions.add(cp.getSessio(dia,h,a.get(0),a.get(1),a.get(2),nomHorari,nomPlaEstudis));
            }
            Object[] o=sessions.toArray();
            tm.addRow(o);
        }
        
    }
    
    void inicia() {
        dillunsRadioButton.doClick();
        String text=("Horari : "+ nomHorari +" del Pla d'Estudis: "+nomPlaEstudis);
        nomText.setText(text);
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
            if(!e.getValueIsAdjusting()){
                    int row=jTable1.getSelectedRow();
                    int col=jTable1.getSelectedColumn();
                    if(row!=-1){
                        if(col!=-1 && col!=0){
                            classeActual[0]=dia;
                            classeActual[1]=(tm.getValueAt(row,0).toString());
                            classeActual[2]=(jTable1.getColumnModel().getColumn(col).getHeaderValue().toString());
                            if(!(classeActual[0].equals(classe1[0]) && classeActual[1].equals(classe1[1]) && classeActual[2].equals(classe1[2]))){
                            sessio2.setText(sessio1.getText());
                            classe2[0]=classe1[0];
                            classe2[1]=classe1[1];
                            classe2[2]=classe1[2];
                                    
                            sessio1.setText(tm.getValueAt(row, col).toString());
                            classe1[0]=dia;
                            classe1[1]=(tm.getValueAt(row,0).toString());
                            classe1[2]=(jTable1.getColumnModel().getColumn(col).getHeaderValue().toString());
                            }
                        }
                    }
                }
            }
            });

        
        jTable1.getColumnModel().getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(!e.getValueIsAdjusting()){
                    int row=jTable1.getSelectedRow();
                    int col=jTable1.getSelectedColumn();
                    if(row!=-1){
                        if(col!=-1 && col!=0){
                            classeActual[0]=dia;
                            classeActual[1]=(tm.getValueAt(row,0).toString());
                            classeActual[2]=(jTable1.getColumnModel().getColumn(col).getHeaderValue().toString());
                            if(!(classeActual[0].equals(classe1[0]) && classeActual[1].equals(classe1[1]) && classeActual[2].equals(classe1[2]))){
                            sessio2.setText(sessio1.getText());
                            classe2[0]=classe1[0];
                            classe2[1]=classe1[1];
                            classe2[2]=classe1[2];
                                    
                            sessio1.setText(tm.getValueAt(row, col).toString());
                            classe1[0]=dia;
                            classe1[1]=(tm.getValueAt(row,0).toString());
                            classe1[2]=(jTable1.getColumnModel().getColumn(col).getHeaderValue().toString());
                            }
                        }
                    }
                }
            }
            });
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JRadioButton dijousRadioButton;
    private javax.swing.JRadioButton dillunsRadioButton;
    private javax.swing.JRadioButton dimartsRadioButton;
    private javax.swing.JRadioButton dimecresRadioButton;
    private javax.swing.JRadioButton divendresRadioButton;
    private javax.swing.JButton intercanviarButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomText;
    private javax.swing.JTextField sessio1;
    private javax.swing.JTextField sessio2;
    // End of variables declaration//GEN-END:variables
  
}
