/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacio;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class vistaCorrequisits extends javax.swing.JPanel {
    CtrlPresentacio cp;
    String nomAssignatura;
    String nomPlaEstudis;
    
    /**
     * Creates new form vistaCorrequisits
     */
    public vistaCorrequisits(CtrlPresentacio cp, String nomAssignatura, String nomPlaEstudis) {
        this.nomAssignatura=nomAssignatura;
        this.nomPlaEstudis=nomPlaEstudis;
        this.cp=cp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        afegirCorrequisitButton = new javax.swing.JButton();
        eliminarCorrequisitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assignatura", "Fase", "CapacitatGrup", "CapacitatSubGrups", "Matriculats", "TipusSubgrup", "NumSessions", "Duracio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jScrollPane3.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable2.setBackground(new java.awt.Color(204, 204, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assignatura", "Fase", "CapacitatGrup", "CapacitatSubGrups", "Matriculats", "TipusSubgrup", "NumSessions", "Duracio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable2);

        jLabel1.setText("Correquisits actuals");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        afegirCorrequisitButton.setText("Afegir Correquisit");
        afegirCorrequisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirCorrequisitButtonActionPerformed(evt);
            }
        });

        eliminarCorrequisitButton.setText("Eliminar Correquisit");
        eliminarCorrequisitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCorrequisitButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Assignatures PlaEstudis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(eliminarCorrequisitButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(afegirCorrequisitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cancelButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afegirCorrequisitButton)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarCorrequisitButton)
                .addGap(53, 53, 53)
                .addComponent(cancelButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
       cp.assignatures();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void afegirCorrequisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirCorrequisitButtonActionPerformed
        int col=jTable1.getSelectedColumn();
        int row=jTable1.getSelectedRow();
        if (col != -1){
            if (row != -1) {
                String nomAssignaturaE=jTable1.getValueAt(row,0).toString();
                String fase=jTable1.getValueAt(row,1).toString();
                String capacitatGrup=jTable1.getValueAt(row,2).toString();
                String capacitatSubGrup=jTable1.getValueAt(row,3).toString();
                String matriculats=jTable1.getValueAt(row,4).toString();
                String tipusSubGrup=jTable1.getValueAt(row,5).toString();
                String numSessions=jTable1.getValueAt(row,6).toString();
                String duracio=jTable1.getValueAt(row,7).toString();

                cp.afegirCorrequisit(nomAssignaturaE, fase, capacitatGrup, capacitatSubGrup, matriculats, tipusSubGrup, numSessions, duracio,nomAssignatura, nomPlaEstudis);
            }
        }
    }//GEN-LAST:event_afegirCorrequisitButtonActionPerformed

    private void eliminarCorrequisitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCorrequisitButtonActionPerformed
        int col=jTable2.getSelectedColumn();
        int row=jTable2.getSelectedRow();
        if (col != -1){
            if (row != -1) {
                String nomAssignaturaE=jTable2.getValueAt(row,0).toString();
                cp.esborrarCorrequisit(nomAssignaturaE,nomAssignatura,nomPlaEstudis);
                DefaultTableModel tm = (DefaultTableModel) jTable2.getModel();
                tm.removeRow(jTable2.getSelectedRow());
            }
        }
    }//GEN-LAST:event_eliminarCorrequisitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afegirCorrequisitButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton eliminarCorrequisitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    void inicia() {
        cp.getAssignaturesVistaCorrequisits(nomAssignatura, nomPlaEstudis);
    }

    void afegirAssignaturaPlaEstudis(String nomAssignatura, String fase, String capacitatGrup, String capacitatSubgrup, String matriculats, String tipusSubgrup, String numSessions, String duracio) {
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.addRow(new Object[]{nomAssignatura, fase, capacitatGrup, capacitatSubgrup, matriculats, tipusSubgrup, numSessions, duracio});
    }
    
    void afegirAssignaturaCorrequisit(String nomAssignatura, String fase, String capacitatGrup, String capacitatSubGrup, String matriculats, String tipusSubGrup, String numSessions, String duracio) {
        DefaultTableModel tm = (DefaultTableModel) jTable2.getModel();
        tm.addRow(new Object[]{nomAssignatura, fase, capacitatGrup, capacitatSubGrup, matriculats, tipusSubGrup, numSessions, duracio});
    }
}
