/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacio;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class vistaAules extends javax.swing.JPanel {
    private CtrlPresentacio cp;
    String[] info= new String[3];
    /**
     * Creates new form vistaAules
     * @param cp
     */
    public vistaAules(CtrlPresentacio cp) {
        this.cp=cp;
        initComponents();
    }
    
    public void inicia(){
       cp.getAulesVistaAules();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afegirAulaButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        eliminarAulaButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        modificarAulaButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        afegirAulaButton.setText("Afegir Aula");
        afegirAulaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirAulaButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aula", "Capacitat", "Tipus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        eliminarAulaButton.setText("Eliminar Aula");
        eliminarAulaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAulaButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        modificarAulaButton.setText("Modificar Aula");
        modificarAulaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAulaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(afegirAulaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarAulaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(modificarAulaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(afegirAulaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarAulaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarAulaButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(cancelButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void afegirAulaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirAulaButtonActionPerformed
       infoAulesDialog i = new infoAulesDialog(new javax.swing.JFrame(),true,cp,info,false);
       i.setVisible(true);
    }//GEN-LAST:event_afegirAulaButtonActionPerformed

    private void eliminarAulaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAulaButtonActionPerformed

        int col=jTable1.getSelectedColumn();
        int row=jTable1.getSelectedRow();
        if (col != -1){
            if (row != -1) {
                errorDialog ce= new errorDialog(new javax.swing.JFrame(),true,jTable1.getValueAt(row, 0).toString(),"",false);
                ce.setVisible(true);
                if(ce.getReturnStatus()==1){
                    String nomAula=jTable1.getValueAt(row,0).toString();
                    cp.esborrarAula(nomAula);
                    DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                    tm.removeRow(jTable1.getSelectedRow());
                }
            }
        }
    }//GEN-LAST:event_eliminarAulaButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cp.menu();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void modificarAulaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAulaButtonActionPerformed
        int col=jTable1.getSelectedColumn();
        int row=jTable1.getSelectedRow();
        if (col != -1){
            if (row != -1) {
                String nomAula=jTable1.getValueAt(row,0).toString();
                String capacitat=jTable1.getValueAt(row,1).toString();
                String tipus=jTable1.getValueAt(row,2).toString();
                info[0]=nomAula;
                info[1]=capacitat;
                info[2]=tipus;
                
                DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                tm.removeRow(jTable1.getSelectedRow());
                
                infoAulesDialog i = new infoAulesDialog(new javax.swing.JFrame(),true,cp,info,true);
                i.setVisible(true);
                                
            }
        }
    }//GEN-LAST:event_modificarAulaButtonActionPerformed
    public void afegirAula(String nom,String capacitat,String tipus){

        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.addRow(new Object[]{nom, capacitat, tipus});
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afegirAulaButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton eliminarAulaButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificarAulaButton;
    // End of variables declaration//GEN-END:variables
}
