/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacio;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class vistaHoraris extends javax.swing.JPanel {
    String nomPlaEstudis;
    CtrlPresentacio cp;

    /**
     * Creates new form vistaHoraris
     */
    public vistaHoraris(CtrlPresentacio cp, String nomPlaEstudis) {
        this.cp=cp;
        this.nomPlaEstudis=nomPlaEstudis;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        crearHorariButton = new javax.swing.JButton();
        visualitzarHorariButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        eliminarHorariButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Horari"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        crearHorariButton.setText("Crear Horari");
        crearHorariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearHorariButtonActionPerformed(evt);
            }
        });

        visualitzarHorariButton.setText("Visualitzar Horari");
        visualitzarHorariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualitzarHorariButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        eliminarHorariButton.setText("Eliminar Horari");
        eliminarHorariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarHorariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(crearHorariButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(visualitzarHorariButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(eliminarHorariButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearHorariButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visualitzarHorariButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarHorariButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addGap(66, 66, 66)
                .addComponent(cancelButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cp.plaestudis();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void eliminarHorariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarHorariButtonActionPerformed
        int col=jTable1.getSelectedColumn();
        int row=jTable1.getSelectedRow();
        if (col != -1){
            if (row != -1) {
                errorDialog ce= new errorDialog(new javax.swing.JFrame(),true,jTable1.getValueAt(row, 0).toString(),"",false);
                ce.setVisible(true);
                if(ce.getReturnStatus()==1){
                    String nomHorari=jTable1.getValueAt(row,0).toString();
                    cp.esborrarHorari(nomHorari,nomPlaEstudis);
                    DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                    tm.removeRow(jTable1.getSelectedRow());
                }
            }
        }
    }//GEN-LAST:event_eliminarHorariButtonActionPerformed

    private void visualitzarHorariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualitzarHorariButtonActionPerformed
        int col=jTable1.getSelectedColumn();
        int row=jTable1.getSelectedRow();
        if (col != -1){
            if (row != -1) {
                String nomHorari=jTable1.getValueAt(row,0).toString();
                cp.visualitzarHorari(nomHorari,nomPlaEstudis);
            }
        }
    }//GEN-LAST:event_visualitzarHorariButtonActionPerformed

    private void crearHorariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearHorariButtonActionPerformed
        cp.creaInfoHoraris(nomPlaEstudis);
    }//GEN-LAST:event_crearHorariButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton crearHorariButton;
    private javax.swing.JButton eliminarHorariButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton visualitzarHorariButton;
    // End of variables declaration//GEN-END:variables

    void inicia() throws Exception {
        cp.carregar_pla(nomPlaEstudis);
        cp.getHorarisPlaEstudis(nomPlaEstudis);
    }

    void afegirHorari(String nomHorari) {
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.addRow(new Object[]{nomHorari});
    }
}
