/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacio;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class vistaAssignatures extends javax.swing.JPanel {
    String nomPlaEstudis;
    CtrlPresentacio cp;
    String[] info= new String[8];
    /**
     * Creates new form vistaAssignatures
     */
    public vistaAssignatures(CtrlPresentacio cp, String nomPlaEstudis) {
        this.nomPlaEstudis=nomPlaEstudis;
        this.cp=cp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        crearAssignaturaButton = new javax.swing.JButton();
        eliminarAssignaturaButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        modificarCorrequisitsAssignaturaButton = new javax.swing.JButton();
        modificarAssignaturaButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assignatura", "Fase", "CapacitatGrup", "CapacitatSubGrups", "Matriculats", "TipusSubgrup", "NumSessions", "Duracio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        crearAssignaturaButton.setText("Crear Assignatura");
        crearAssignaturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAssignaturaButtonActionPerformed(evt);
            }
        });

        eliminarAssignaturaButton.setText("Eliminar Assignatura");
        eliminarAssignaturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAssignaturaButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        modificarCorrequisitsAssignaturaButton.setText("Modificar Correquisits Assignatura");
        modificarCorrequisitsAssignaturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarCorrequisitsAssignaturaButtonActionPerformed(evt);
            }
        });

        modificarAssignaturaButton.setText("Modificar Assignatura");
        modificarAssignaturaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAssignaturaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(crearAssignaturaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificarCorrequisitsAssignaturaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(modificarAssignaturaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarAssignaturaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearAssignaturaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarAssignaturaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarCorrequisitsAssignaturaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarAssignaturaButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(62, 62, 62)
                .addComponent(cancelButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearAssignaturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAssignaturaButtonActionPerformed
        infoAssignaturesDialog i = new infoAssignaturesDialog(new javax.swing.JFrame(),true,cp,info,false);
        i.setVisible(true);
    }//GEN-LAST:event_crearAssignaturaButtonActionPerformed

    private void eliminarAssignaturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAssignaturaButtonActionPerformed
        int col=jTable1.getSelectedColumn();
        int row=jTable1.getSelectedRow();
        if (col != -1){
            if (row != -1) {
                errorDialog ce= new errorDialog(new javax.swing.JFrame(),true,jTable1.getValueAt(row, 0).toString(),"",false);
                ce.setVisible(true);
                if(ce.getReturnStatus()==1){
                    String nomAssignatura=jTable1.getValueAt(row,0).toString();
                    cp.esborrarAssignatura(nomAssignatura,nomPlaEstudis);
                    DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                    tm.removeRow(jTable1.getSelectedRow());
                }
            }
        }
    }//GEN-LAST:event_eliminarAssignaturaButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cp.plaestudis();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void modificarCorrequisitsAssignaturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarCorrequisitsAssignaturaButtonActionPerformed
        int col=jTable1.getSelectedColumn();
        int row=jTable1.getSelectedRow();
        if (col != -1){
            if (row != -1) {
                String nomAssignatura=jTable1.getValueAt(row,0).toString();
                cp.creaVistaCorrequisits(nomAssignatura,nomPlaEstudis);
            }
        }
    }//GEN-LAST:event_modificarCorrequisitsAssignaturaButtonActionPerformed

    private void modificarAssignaturaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAssignaturaButtonActionPerformed
        int col=jTable1.getSelectedColumn();
        int row=jTable1.getSelectedRow();
        if (col != -1){
            if (row != -1) {
                String nomAssignatura=jTable1.getValueAt(row,0).toString();
                String fase=jTable1.getValueAt(row,1).toString();
                String capacitatGrup=jTable1.getValueAt(row,2).toString();
                String capacitatSubGrup=jTable1.getValueAt(row,3).toString();
                String matriculats=jTable1.getValueAt(row,4).toString();
                String tipusSubGrup=jTable1.getValueAt(row,5).toString();
                String numSessions=jTable1.getValueAt(row,6).toString();
                String duracio=jTable1.getValueAt(row,7).toString();
                info[0]=nomAssignatura;
                info[1]=fase;
                info[2]=capacitatGrup;
                info[3]=capacitatSubGrup;
                info[4]=matriculats;
                info[5]=tipusSubGrup;
                info[6]=numSessions;
                info[7]=duracio;
                DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                tm.removeRow(jTable1.getSelectedRow());
                
                infoAssignaturesDialog i = new infoAssignaturesDialog(new javax.swing.JFrame(),true,cp,info,true);
                i.setVisible(true);
                                
            }
        }                 
    }//GEN-LAST:event_modificarAssignaturaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton crearAssignaturaButton;
    private javax.swing.JButton eliminarAssignaturaButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificarAssignaturaButton;
    private javax.swing.JButton modificarCorrequisitsAssignaturaButton;
    // End of variables declaration//GEN-END:variables

    void inicia() {
        cp.getAssignaturesVistaAssignatures(nomPlaEstudis);
    }

    void afegirAssignatura(String nomAssignatura, String fase, String capacitatGrup, String capacitatSubgrup, String matriculats, String tipusSubgrup, String numSessions, String duracio) {
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        tm.addRow(new Object[]{nomAssignatura, fase, capacitatGrup, capacitatSubgrup, matriculats, tipusSubgrup, numSessions, duracio});
    }

    String getNomPlaEstudis() {
        return nomPlaEstudis;
    }
}
